site_name: NDN 101
repo_url: https://github.com/named-data/ndn-101

theme:
  name: material
  icon:
    logo: material/network
  favicon: img/ndn.png
  palette:
    primary: deep orange
  features:
    - content.tabs.link
    - navigation.footer
    - navigation.expand
    - content.code.copy

plugins:
  - search
  - bibtex:
      bib_file: ndn.bib
      bib_by_default: true
      csl_file: acm-sig-proceedings.csl

nav:
  - 'index.md'
  - 'getting-started.md'
  - Connectivity:
    - 'connectivity/packet-format.md'
    - 'connectivity/building-networks.md'
    - 'connectivity/communication-model.md'
    - 'connectivity/forwarding.md'
    - 'connectivity/routing.md'
    - 'connectivity/testbed.md'
  - Security:
    - 'security/introduction.md'
    - 'security/trust-model.md'
    - 'security/signatures.md'
  - 'sync.md'
  - 'storage.md'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/iframe-message.js
