[tool.poetry]
package-mode = false
name = "ndn-101"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-material = "^9.5.3"
mkdocs-bibtex = "^2.11.0"
pypandoc-binary = "^1.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
